# Generated by Django 5.2.8 on 2025-11-29 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(default='bi-bookmark', max_length=50)),
                ('cor', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AddField(
            model_name='receita',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='receitas_favoritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receita',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receita',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='receitas', to='receitas.categoria'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='receitas.receita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='receitas/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_extras', to='receitas.receita')),
            ],
            options={
                'verbose_name': 'Foto Extra',
                'verbose_name_plural': 'Fotos Extras',
            },
        ),
    ]
